# Generated by Django 4.0.3 on 2024-04-23 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes'), (150, '150 minutes'), (180, '180 minutes')])),
                ('event_type', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(null=True)),
                ('invitee_description', models.TextField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('finalized_start_time', models.DateTimeField(null=True)),
                ('finalized_end_time', models.DateTimeField(null=True)),
                ('finalized_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('D', 'Deleted/Canceled'), ('A', 'Pending Availability'), ('C', 'Pending Final Confirmation'), ('F', 'Finalized')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
