# Generated by Django 4.0.3 on 2024-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finalized_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='finalized_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='finalized_start_time',
            field=models.TimeField(null=True),
        ),
    ]
