# Generated by Django 4.0.3 on 2024-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finalized_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finalized_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
