# Generated by Django 4.0.3 on 2024-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_finalized_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitee_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('other', 'Other')], max_length=50),
        ),
    ]
