# Generated by Django 4.0.3 on 2024-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_finalized_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitee_description',
            field=models.TextField(null=True),
        ),
    ]
