# Generated by Django 4.0.3 on 2024-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_invitee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('other', 'Other')], max_length=50),
        ),
    ]
