# Generated by Django 5.0.3 on 2024-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')])),
                ('event_type', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video')], max_length=50)),
                ('description', models.TextField()),
                ('deadline', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('D', 'Deleted/Canceled'), ('A', 'Pending Availability'), ('C', 'Pending Final Confirmation'), ('F', 'Finalized')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
