# Generated by Django 4.0.3 on 2024-04-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
