# Generated by Django 5.0.3 on 2024-03-29 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('events', '0001_initial'),
        ('timeblocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_timeblock', to='events.event'),
        ),
        migrations.AddField(
            model_name='availability',
            name='timeblock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeblocks.availabilitytimeblock'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'timeblock_id'), name='unique_availability'),
        ),
    ]
