# Generated by Django 4.0.3 on 2024-04-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_range',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_range',
        ),
    ]
