# Generated by Django 4.0.3 on 2024-04-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_remove_availability_end_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
    ]
