# Generated by Django 5.0.3 on 2024-03-23 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='preference_type',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timeblocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
