# Generated by Django 5.0.3 on 2024-03-24 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_host_id_remove_event_invitee_id'),
        ('timeblocks_events', '0002_alter_timeblock_is_finalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeblock',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'date', 'start_time', 'end_time', 'preference_type', 'is_finalized'), name='unique_timeblock'),
        ),
    ]
