# Generated by Django 4.2.10 on 2024-03-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_host_alter_event_invitee"),
        ("timeblocks_events", "0003_timeblock_unique_timeblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeblocks",
                to="events.event",
            ),
        ),
    ]
