# Generated by Django 4.2.10 on 2024-03-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_availability_event"),
        ("timeblocks_events", "0004_alter_timeblock_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeblocks",
                to="events.event",
            ),
        ),
    ]
