# Generated by Django 4.2.10 on 2024-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_host_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="event",
            name="deadline",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="finalized_timeblock_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Deleted/Canceled"),
                    ("A", "Pending Availability"),
                    ("C", "Pending Final Confirmation"),
                    ("F", "Finalized"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="host_id",
            field=models.IntegerField(),
        ),
    ]
