# Generated by Django 4.2.10 on 2024-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_is_deleted_event_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="host_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="invitee_id",
            field=models.IntegerField(default=1),
        ),
    ]
