# Generated by Django 4.2.10 on 2024-03-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_host_id_alter_event_invitee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(default=1)),
                ("timeblock_id", models.IntegerField(verbose_name="Timeblock ID")),
                ("start_range", models.DateField(verbose_name="Start Date")),
                ("end_range", models.DateField(verbose_name="End Date")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
        ),
    ]
