# Generated by Django 4.2.10 on 2024-03-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="host_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="invitee_id",
        ),
    ]
