# Generated by Django 4.2.10 on 2024-03-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_host_alter_event_invitee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Event",
            ),
        ),
    ]
