# Generated by Django 4.2.10 on 2024-03-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timeblocks_events", "0005_alter_timeblock_event"),
        ("events", "0010_alter_availability_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="finalized_timeblock_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_timeblock",
                to="timeblocks_events.timeblock",
            ),
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
    ]
