# Generated by Django 5.0.3 on 2024-03-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_date_joined_remove_user_last_updated_and_more'),
        ('accounts', '0006_user_first_name_user_last_name_user_phone_number'),
    ]

    operations = [
    ]
