# Generated by Django 4.2.10 on 2024-03-25 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timeblocks_events", "0005_alter_timeblock_event"),
        ("events", "0010_alter_availability_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_range", models.DateField(verbose_name="Start Date")),
                ("end_range", models.DateField(verbose_name="End Date")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_timeblock",
                        to="events.event",
                    ),
                ),
                (
                    "timeblock_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timeblocks_events.timeblock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
