# Generated by Django 4.2.10 on 2024-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("user", "event", "timeblock_id"), name="unique_availability"
            ),
        ),
    ]
