# Generated by Django 4.2.10 on 2024-03-20 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0002_alter_contact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="user",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
