# Generated by Django 4.2.10 on 2024-03-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0003_remove_contact_user_contact_contact_contact_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="removed",
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
